/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_start_6 (void);
GtkWidget* create_window_add_client_6 (void);
GtkWidget* create_window_admin_start_6 (void);
GtkWidget* create_window_admin_clients_6 (void);
GtkWidget* create_window_modifier_supprimer_clients_6 (void);
GtkWidget* create_window_modifier_clients_6 (void);
GtkWidget* create_window_admin_vol_6 (void);
GtkWidget* create_window_ajout_vol_6 (void);
GtkWidget* create_window_modifier_supprimer_vols (void);
GtkWidget* create_window_modifier_vols (void);
GtkWidget* create_window_admin_travel_6 (void);
GtkWidget* create_window_add_travel_6 (void);
GtkWidget* create_window_modifier_supprimer_travel_6 (void);
GtkWidget* create_window_modifier_travel_6 (void);
GtkWidget* create_window_admin_hotel_6 (void);
GtkWidget* create_window_add_hotel_6 (void);
GtkWidget* create_window_modifier_supprimer_hotel_6 (void);
GtkWidget* create_window_modifier_hotel_6 (void);
